kind: pipeline
type: docker
name: default

steps:
  - name: validate
    image: alpine:3.20
    commands:
      - echo "Validating repo contents..."
      - test -f site/index.html
      - test -f site/styles.css

  - name: build
    image: node:20-alpine
    commands:
      - sh -c "echo 'Pretend build: copy static files to dist/'"
      - sh -c "mkdir -p dist"
      - sh -c "cp -r site/* dist/"
      - sh -c "ls -la dist"

  - name: test
    image: alpine:3.20
    commands:
      - sh -c "echo 'Run a simple test...'"
      - sh -c "grep -q 'Hello Woodpecker' dist/index.html"
      - sh -c "echo 'All good!'"

  - name: package
    image: alpine:3.20
    commands:
      - sh -c "tar -czf dist.tar.gz dist"
      - sh -c "ls -lh dist.tar.gz"
